name: Android

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
    
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
            sudo chmod +x /usr/bin/yq

      - name: Extract version from pubspec.yaml
        run: |
            version=$(yq eval '.version' pubspec.yaml)
            echo "version=${version}" >> $GITHUB_ENV
        
      - name: Sign Apk
        run: |
          echo '${{ secrets.KEYSTORE }}' | base64 --decode > upload-keystore.jks
          echo '${{ secrets.KEY_PROPERTIES }}' > key.properties
      
      - name: Build Apk
        run: |
          flutter build apk --release
          mv build/app/outputs/flutter-apk/app-release.apk MindfulGuard_android.apk
  
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
            files: MindfulGuard_android.apk
            tag_name: ${{ env.version }}
        env:
            GITHUB_TOKEN: ${{ secrets.ACTIONS }}
